services:
  - type: web
    name: agi-house-demo-backend
    plan: starter
    runtime: python
    repo: https://github.com/pateli18/agi-house-production-hack
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port 8000
    envVars:
      - key: WEB_CONCURRENCY
        value: 1
      - key: LOG_LEVEL
        value: INFO
      - key: PORT
        value: 8000